In [1]:
print("Welcome")

Welcome


In [ ]:
# numpy:-


it is used for math calculations

In [ ]:
# data_Type :- ndarrays 

In [3]:
import numpy as np  # alieas name 

In [4]:
array_one = np.array([1,2,3])

In [5]:
print(array_one)

[1 2 3]


In [6]:
num = [6,5,4]

In [7]:
array_two = np.array(num)

In [8]:
print(array_two)

[6 5 4]


In [13]:
array_two[0]

6

In [14]:
type(array_two[0])

numpy.int32

In [ ]:
# array is nothing but a normal list


# diff betwn the list and numpy array

# numpy array is very efficent as comapred to normal list

# list is resizabale 

# array is not resizable 

# list accepts any mixed types, coming to array accpets only  one type


In [9]:
array_of_zeros = np.zeros((3,4))


# 3 rows
# 4 colmns

In [10]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# How to print a array with ones


# np.ones()

In [11]:
array_of_ones = np.ones((4,5))

# 4 rows
# 5 columns

In [12]:
print(array_of_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
array_of_ones[0][0]

1.0

In [16]:
type(array_of_ones[0][0])

numpy.float64

In [ ]:
# numpy will always prints or returns float values

In [ ]:
# req:- how to return init values in array

In [17]:
array_of_ones_int = np.ones((5,5),dtype = np.int16)

In [18]:
print(array_of_ones_int)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
# type(array_of_ones_int[0][0])

numpy.int16

In [ ]:
# what is int 16

# to represnt data in int values we have to use the dtypes like int16, int32, int64
                int16
                int32
                int64

            
# based on the array size and elements we use...!!

In [ ]:
# arange ----> numpy


arange is nothing but a range function in python

In [ ]:
# req:- i want an array consisting of numbers from 1 to 30

In [22]:
# arange()

array_arange = np.arange(1,30+1) # last value is always exclusive

In [23]:
print(array_arange)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [ ]:
# arange() with step count


# req:- i want even numbers from 2 to 30

In [26]:
array_step = np.arange(2,30+2,2)

# array_step = np.arange(initial_value, final_value+2, step_count)

In [27]:
print(array_step)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
